#+title: Emacs Early Init
#+author: mattiasdrp
#+date: <2022-08-17 Wed>
#+language: en_US
#+property: header-args :results silent :exports code :tangle yes

#+keywords: Emacs

Literate configuration for [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html][early-init.el]].

:PROPERTIES:
:TOC:      :include all
:END:

:CONTENTS:

:END:

* Header

#+BEGIN_SRC emacs-lisp
  ;;; early-init.el --- Emacs early init -*- lexical-binding: t -*-
  ;;

  ;; Copyright (c) 2022 mattiasdrp and contributors.

  ;; Author: mattiasdrp
  ;; Maintainer: mattiasdrp <https://github.com/mattiasdrp>
  ;; Created: 17 august 2022
  ;; Version: 1.0
  ;; Licence: MIT
  ;; Keywords: emacs, init, convenience, configuration
  ;; URL: https://github.com/mattiasdrp/pokemacs

  ;;; Commentary:

  ;; This file is an early-init file for Emacs. It will be executed before
  ;; init.el when emacs is loaded.

  ;; This file IS NOT intended to be edited! It was generated by early-init.org.
  ;; If you want to change it, edit early-init.org then M-x org-babel-tangle

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; Code:

#+END_SRC

* Decrease GC frequency

By increasing the GC threshold we ensure that it will run less frequently and thus lead to a faster start-up.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold 100000000)
#+END_SRC

* Increase data read from processes

This is useful for lsp, notably

#+BEGIN_SRC emacs-lisp
  (setq read-process-output-max (* 1024 1024)) ;; 1mb
#+END_SRC

* Native compilation settings

Disable warnings, async compilation and cache directory for native compilation.

#+BEGIN_SRC emacs-lisp
  ;;; Native compilation settings
  (when (featurep 'native-compile)
    ;; Silence compiler warnings as they can be pretty disruptive
    (setq native-comp-async-report-warnings-errors nil)

    ;; Make native compilation happens asynchronously
    (setq native-comp-deferred-compilation t)

    ;; Set the right directory to store the native compilation cache
    ;; NOTE: the method for setting the eln-cache directory depends on the emacs version
    (when (fboundp 'startup-redirect-eln-cache)
      (if (version< emacs-version "29")
          (add-to-list 'native-comp-eln-load-path (convert-standard-filename (expand-file-name "var/eln-cache/" user-emacs-directory)))
        (startup-redirect-eln-cache (convert-standard-filename (expand-file-name "var/eln-cache/" user-emacs-directory))))))
#+END_SRC

* Disable package-enable-at-startup

Package initialize occurs automatically, before init.el is loaded, but after early-init.el. We handle package initialization, so we must prevent Emacs from doing it early.

#+BEGIN_SRC emacs-lisp
  (setq package-enable-at-startup nil)
#+END_SRC

* Reduce Redisplay

To reduce slowdowns caused by early redisplays when loading, the following code will reduce the amount of times Emacs redisplays when setting up windows. This idea came from the Doom Emacs early-init.el file.

#+BEGIN_SRC emacs-lisp
  (setq-default inhibit-redisplay t
                inhibit-message t)

  (add-hook 'window-setup-hook
            (lambda ()
              (setq-default inhibit-redisplay nil
                            inhibit-message nil)
              (redisplay)))
#+END_SRC

* Unset file-name-handler-alist

Every file opened and loaded by Emacs will run through this list to check for a proper handler for the file, but during startup, it won’t need any of them.

#+BEGIN_SRC emacs-lisp
  (defvar file-name-handler-alist-original file-name-handler-alist)
  (setq file-name-handler-alist nil)
#+END_SRC

* Disable site-run-file

#+BEGIN_SRC emacs-lisp
  (setq site-run-file nil)
#+END_SRC

* Disable Unnecessary Interface

It will be faster to disable them here before they've been initialized.

#+BEGIN_SRC emacs-lisp
  (push '(tool-bar-lines . 0) default-frame-alist)
  (push '(tool-bar-mode . 0) default-frame-alist)
  (push '(vertical-scroll-bars) default-frame-alist)
#+END_SRC

* Initial mode

Make the initial buffer load faster by setting its mode to fundamental-mode

#+BEGIN_SRC emacs-lisp
  (customize-set-variable 'initial-major-mode 'fundamental-mode)
#+END_SRC

* End

#+BEGIN_SRC emacs-lisp
  (provide 'early-init)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; early-init.el ends here
#+END_SRC
