#+title: Pokemacs literate config file
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Table of Contents
:PROPERTIES:
:TOC:      :include all :ignore (this)
:END:

:CONTENTS:
- [[#documentation][Documentation]]
- [[#system][System]]
  - [[#emacs][Emacs]]
    - [[#building][Building]]
      - [[#from-sources][From sources]]
      - [[#with-guix][With guix]]
  - [[#languages][Languages]]
    - [[#combobulate][Combobulate]]
    - [[#lsp][LSP]]
    - [[#flyspell][Flyspell]]
    - [[#ocaml][OCaml]]
    - [[#rust][Rust]]
    - [[#python][Python]]
  - [[#once-emacs-is-installed][Once emacs is installed:]]
  - [[#fonts][Fonts]]
  - [[#configure-packages][Configure packages]]
  - [[#git-hosts-and-forges][Git hosts and forges]]
    - [[#ghub][Ghub]]
    - [[#code-review][Code Review]]
  - [[#external-files][External files]]
- [[#emacs-config][Emacs config]]
- [[#big-thanks][Big Thanks]]
- [[#todos][Todos]]
:END:

* Documentation
:PROPERTIES:
:CUSTOM_ID: documentation
:END:

Read the [[file:manual.org][manual]], you won't regret it.

* System
:PROPERTIES:
:CUSTOM_ID: system
:END:

** Emacs
:PROPERTIES:
:CUSTOM_ID: emacs
:END:

 - Your version of emacs should be at least 27.1

*** Building
:PROPERTIES:
:CUSTOM_ID: building
:END:

**** From sources
:PROPERTIES:
:CUSTOM_ID: from-sources
:END:

- For this you need to either:
  - ~git submodule init && git submodule update~ will download my own version of emacs that should be optimised for lsp
  - clone [[https://github.com/emacs-mirror/emacs][the emacs repository]] and either checkout the ~emacs.27.1~ (or higher) branch or compile from the ~main~ branch.
- I tend to forget what dependencies are needed by emacs so here is the command I usually invoke before configuring and compiling emacs:

  #+begin_src sh
    sudo apt install -y autoconf make gcc texinfo libgtk-3-dev libxpm-dev \
      libjpeg-dev libgif-dev libtiff5-dev libgnutls28-dev libncurses5-dev \
      libjansson-dev libharfbuzz-dev libharfbuzz-bin imagemagick libmagickwand-dev \
      libgccjit-14-dev libgccjit0 gcc-14 libjansson4 libjansson-dev libtree-sitter-dev \
      xaw3dg-dev texinfo libx11-dev libenchant-2-dev pkgconf
  #+end_src

  #+begin_src sh
    sudo dnf install autoconf make gcc texinfo gtk3 gtk3-devel libXpm-devel \
      libjpeg-turbo-devel giflib-devel libtiff-devel gnutls-devel ncurses-devel \
      jansson-devel harfbuzz-devel harfbuzz ImageMagick ImageMagick-devel libgccjit-devel \
      libtree-sitter libtree-sitter-devel webkit2gtk4.1-devel Xaw3d-devel texinfo \
      libX11-devel enchant-devel pkgconf
  #+end_src

  #+begin_src sh
    export CC="gcc-14"
  #+end_src

- If you feel confident and better than me at installing emacs from scratch, don't hesitate to tell me where I'm wrong, I always love to learn
- Once
  #+begin_src sh
    ./autogen.sh
  #+end_src

  and
  #+begin_src sh
    ./configure --with-native-compilation -with-json --with-modules --with-harfbuzz --without-compress-install --with-threads --with-included-regex --with-x-toolkit=gtk3 --with-zlib --with-jpeg --with-png --with-imagemagick --with-tiff --with-xpm --with-gnutls --with-xft --with-xml2 --with-mailutils --with-tree-sitter
  #+end_src

  tell you you can make,
  #+begin_src sh
    make -j $(nproc)
  #+end_src

  then

  #+begin_src sh
    sudo make install
  #+end_src

**** With guix
:PROPERTIES:
:CUSTOM_ID: with-guix
:END:

- I just follow [[https://systemcrafters.net/craft-your-system-with-guix/installing-the-package-manager/][this link]]

** Languages
:PROPERTIES:
:CUSTOM_ID: languages
:END:

*** Combobulate
:PROPERTIES:
:CUSTOM_ID: combobulate
:END:

You need to initialize the ~combobulate~ submodule until it is available on Melpa.

#+begin_src sh
  git submodule init && git submodule update
#+end_src

*** LSP
:PROPERTIES:
:CUSTOM_ID: lsp
:END:

- In your shell config file:
  #+begin_src sh
    export LSP_USE_PLISTS=true
  #+end_src

*** Flyspell
:PROPERTIES:
:CUSTOM_ID: flyspell
:END:

- ~aspell~ will be installed the first time you start emacs but you'll still need to install the dictionaries you want to use. In my case this will be:

  #+begin_src sh
    sudo apt install aspell-fr aspell-en
  #+end_src

*** OCaml
:PROPERTIES:
:CUSTOM_ID: ocaml
:END:

- The best™ way to have an OCaml environment is to install it through opam
  -
    #+BEGIN_SRC shell
      bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"
    #+END_SRC
  - Make sure you answer ~y~ when asked, this will ensure that opam automatically switches env when you move to a directory with a different opam switch
    #+BEGIN_SRC shell
      opam init
    #+END_SRC
- You need to have ~ocamlformat~ and ~ocaml-lsp-server~ installed in your switch
  DEPRECATED: pokemacs is now able to install it for you if they're missing in the current switch
  #+begin_src sh
    opam install ocamlformat ocaml-lsp-server -y
  #+end_src

*** Rust
:PROPERTIES:
:CUSTOM_ID: rust
:END:

- [[https://blog.rust-lang.org/2022/07/01/RLS-deprecation.html][Rust Analyzer]]
  - install [[http://rustup.rs/][rustup]]
    #+begin_src sh
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    #+end_src
  - Update
    #+begin_src sh
      rustup update
    #+end_src
  - Install components
    #+begin_src sh
      rustup component add rust-analysis rust-analyzer rust-src
    #+end_src

*** Python
:PROPERTIES:
:CUSTOM_ID: python
:END:

- Install dependencies
  #+begin_src sh
    sudo apt-get install make build-essential libssl-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
        libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
  #+end_src

- Install pyenv
  #+begin_src sh
    curl https://pyenv.run | $SHELL
  #+end_src

- Setup shell env for pyenv: https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv

- Install python
  #+begin_src sh
    pyenv install 3.10.5
  #+end_src

- Install nvm
  #+begin_src sh
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | $SHELL
  #+end_src

- Upgrade pip
  #+begin_src sh
    python -m pip install --upgrade pip
  #+end_src

- Install pyright and other needed packages
  #+begin_src sh
    pip install pyright black isort yapf
  #+end_src


*** Zig

- Download a prebuilt tarball from https://ziglang.org/download/
- Untar it in the directory of your choice
  #+begin_src shell
    tar -xvzf zig-<ver>.tar.xz -C ~/.zig/zig --strip-components=1
  #+end_src
- Clone the zls repository and build the version corresponding to the zig tarball you downloaded
  #+begin_src shell
    git clone https://github.com/zigtools/zls ~/.zig/zls
  #+end_src
  #+begin_src shell
    cd ~/.zig/zls && zig build -Doptimize=ReleaseSafe
  #+end_src
- If you chose the same paths as in the above commands you have nothing to do. Otherwise, Zig expects to find the binary for ~zig~ and ~zls~ to be able to run LSP. Customize ~lsp-zig-zig-exe-path~ and ~lsp-zig-zls-executable~.

** Once emacs is installed:
:PROPERTIES:
:CUSTOM_ID: once-emacs-is-installed
:END:

Just start emacs and let it install all the packages and dependencies.

** Fonts
:PROPERTIES:
:CUSTOM_ID: fonts
:END:

#+begin_src emacs-lisp
  sudo apt install fonts-firacode fonts-material-design-icons-iconfont texlive-fonts-extra
#+end_src

#+begin_src emacs-lisp
sudo dnf install fira-code-fonts material-icons-fonts texlive-collection-fontsextra
#+end_src

** Configure packages
:PROPERTIES:
:CUSTOM_ID: configure-packages
:END:

After everything is installed you need to run these two commands just once.

- ~M-x all-the-icons-install-fonts~
- ~M-x nerd-icons-install-fonts~
- ~M-x pdf-tools-install~

** Git hosts and forges
:PROPERTIES:
:CUSTOM_ID: git-hosts-and-forges
:END:

*** Ghub
:PROPERTIES:
:CUSTOM_ID: ghub
:END:

[[https://github.com/magit/ghub][Ghub]] is used and needs a bit of tuning first.

In [[file:custom.el][custom.el]] you can see the line ~'(auth-sources '("-/.authinfo"))~, this is where packages looking for authentication sources will look. You can obviously customize it.

Ghub expects to see lines of the following format:

#+begin_src sh
  # for GitHub
  machine api.github.com login <username>^<package> password <token_from_github>
  # for Gitlab
  machine gitlab.com/api/v4 login <username>^<package> password <token_from_gitlab>
#+end_src

For pokemacs you need one line only (working towards gitlab integration):
- ~machine api.github.com login <username>^ghub password <token_from_github>~)
# - ~machine gitlab.com/api/v4 login <username>^ghub password <token_from_github>~)

Ghub also expects you to have set your username for the hosts you use with:

#+begin_src sh
  git config --<global | local> <host>.user <username>
#+end_src

For pokemacs you need to set it for GitHub.

*** Code Review
:PROPERTIES:
:CUSTOM_ID: code-review
:END:

Code review needs authentication tokens for ~forge~ and ~code-review~. Both tokens need the ~repo~ scope active for github and the ~api~ scope for gitlab. You need to store them like this in your ~authinfo~ file:

#+BEGIN_SRC shell
  machine api.github.com login <username>^forge password <token_from_github>
  machine api.github.com login <username>^code-review password <token_from_github>
  machine gitlab.com/api login <username>^forge password <token_from_gitlab>
  machine gitlab.com/api login <username>^code-review password <token_from_gitlab>
#+END_SRC

And, of course, you need to let both tools know who you are:

#+begin_src sh
  git config --<global | local> github.user <username>
  git config --<global | local> gitlab.gitlab.com/api.user <username>
#+end_src

** External files
:PROPERTIES:
:CUSTOM_ID: external-files
:END:

- I have a ~​~/org~ directory that contains 4 files:

#+BEGIN_SRC
  org
  ├── agenda.org
  ├── calendar​_company.org
  ├── calendar​_user.org
  └── orgzly.org
#+END_SRC

- This repository is synchronised on all my devices with [[https://syncthing.net/][Syncthing]] but the directory is checked entirely by org so you can put the files you want in it
- I don't like having things everywhere. That's why I configured org-gcal to synchronise with my company's Google Calendar. For this I needed a secret key that I can't realistically put in a public repository. This key is located in ~~/.secrets/gcal-secrets.json~

#+BEGIN_SRC json
  {
      "org-gcal-client-id": "my_id.apps.googleusercontent.com",
      "org-gcal-client-secret": "my_secret_key",
      "calendar-company": "my_company_calendar_id",
      "calendar-user": "my_user_calendar_id"
  }
#+END_SRC

- Thanks to [[https://www.reddit.com/user/-jz-/][-jz-]]for [[https://www.reddit.com/r/emacs/comments/d1ehpy/security_tip_if_you_push_initel_to_a_public_repo/][this thread]]

Restart emacs and everything should work

* Emacs config
:PROPERTIES:
:CUSTOM_ID: emacs-config
:END:

The emacs config is written as literate programming in [[file:init.org][init.org]] and this file generates the [[file:init.el][init.el]] file (that should never be touched). If you want to try things you can edit [[file:init.org][init.org]] and when you've finished just hit ~C-c C-v t~ (~org-babel-tangle~).

* Big Thanks
:PROPERTIES:
:CUSTOM_ID: big-thanks
:END:

- [[https://github.com/daviwil][daviwil]] for his [[https://github.com/daviwil/emacs-from-scratch][emacs from scratch]] serie
- [[https://github.com/hlissner][hlissner]] for [[https://github.com/doomemacs/doomemacs][doomemacs]]
- Many other that I stupidly didn't store for small config tricks, bug fixes etc that I found on StackOverflow, Reddit, GitHub, personal blogs etc
- Thanks to [[https://github.com/coquera][@coquera]] for forcing me to create a README, this was one big example of procrastination
- Thanks to [[https://github.com/thriim][@thriim]] for the thorough testing
- Thanks to [[https://github.com/remyzorg][@remyzorg]] for being unable to choose

* Todos
:PROPERTIES:
:CUSTOM_ID: todos
:END:

 - [X] Rewrite this README in org
 - [X] Maybe try this "literate" programming thing
 - [ ] I experimented with `emacs-daemon` and `emacsclient` but not enough to make it viable
 - [ ] Complete this TODO list
 - [ ] Add all the remaining thanks
